### ISSUE TITLE
Understanding SV types -- TRA vs INS

### ISSUE THREAD

**Issue by JohnUrban** [fritzsedlazeck/Sniffles#126]
Hi again,

What does Sniffles see as a translocation vs a large insertion?

e.g. if you have a 2 kb piece of chrB inserted into chrA, is that considered INS or TRA? If TRA, then when is it called INS? ... in cases where the insertion couldn't be aligned elsewhere? and also if "TRA", then I guess "translocation" here does not mean chromosomal translocations -- but any scenario where a piece of one sequence is found inside another. . . correct?

Overall -- I ask b/c I was simulating insertions as described above (e.g. 2 kb piece of chrB inserted into chrA) and they were called as TRA. So now I am wondering how to simulate an insertion.

Best,

John

**Comment by fritzsedlazeck** [comment]
Hi John,
Insertion are typically novel sequence. In your case you simulated something like a trnasposon jumping around from one chr to another. Thus it was called as a translocation since one part of the read mapped to chrA and another to chr B. Does that make sense?

You can also check out my tool SURVIVOR that let you simulate multiple SVs including insertions of different sizes. 

Let me know if that helps
Fritz

**Comment by JohnUrban** [comment]
That helps. Thanks. I will also check out SURVIVOR.
