### ISSUE TITLE
why named this software sniffles?

### ISSUE THREAD

**Issue by Niconlsam** [fritzsedlazeck/Sniffles#128]
Hi @fritzsedlazeck ,
 I'm a doctor from Hong Kong,now i am  writing the detailed project book to apply for the fund, i want to know why called this software sniffles? i can not find in your paper.

Thank you for taking a look!

**Comment by fritzsedlazeck** [comment]
Hey @Niconlsam ,
So initially I named it sniffles since I thought it means sniffing around which translates into German with the same name. I shortly afterwards figured out this is not really the case since it is more like having a stuffed nose. Nevertheless, I kinda loved the irony about this and thus I kept the name.

Cheers
Fritz
