### ISSUE TITLE
Sequencing coverage for Nanopore reads?

### ISSUE THREAD

**Issue by BioinformaticsBro** [fritzsedlazeck/Sniffles#137]
Hi everyone, I just watched the structural variant calling webinar on ONT website and would like to try out sniffles. 

In the webinar they show at 15X coverage, you can get ~80% recall and ~90% precision. Is 15X coverage before or after filtering for length and mapping quality (-r Discard read if non of its segment is larger then this. Default: 2kb; -q Minimum mapping quality of alignment to be taken into account. Default: 20)?

![image](https://user-images.githubusercontent.com/37677948/55371184-d95bb280-552f-11e9-8c2b-6df5f691b63a.png)

Is there a good rule of thumb for coverage depth for human genomes? Of course, the more coverage the better, but how much do I need to get decent results? What's the bare minimum coverage that's acceptable (the webinar mentions "high precision and recall even at low read depth" but it's not clear me what's considered low)?

**Comment by philres** [comment]
Hi,

the coverage was computed from the BAM file per chromosome using ```mosdepth --by genome.bed``` where `genome.bed` is a BED file that has one entry per chromosome (produced by ```faidx --transform bed```). The BAM file was not filtered by mapping quality or read length.

The bare minimum completely depends on what you want to do. So I unfortunately can't give you a simple answer. It will depend on whether you look at a diploid or haploid genome, but you mentioned human so let's assume diploid.
The plot you posted gives you a rough idea of what you can expect in terms of precision and recall in a standard WGS human dataset (when compared to the GIAB truth set).
15X is a good place to start in terms of minimum where you will get decent recall at good precision. If you don't care for one or the other you can adjust the min read support cutoff and potentially get away with less. For example if you are only interested in whether a fixed set of SVs you know beforehand are in a given sample or not. On the other hand, if you are looking at a cancer sample where your coverage can vary a lot (because of some regions being extremely amplified), you will probably need more. But even that depends on what you want to do.

**Comment by BioinformaticsBro** [comment]
Hi Philipp, thanks for reaching out, I'm looking forward using Sniffles in my SV analysis. Any idea on when we can expect the workflow to appear on the ONT bioinformatics tutorial page? 

I'm mapping my reads to GRCh38 with decoys. Would you recommend filtering the bam file to keep only Chr 1-22, X & Y before running Sniffles? On my first test, I ran Sniffles with an unfiltered bam file which produced a lot of translocations between real chromosomes and decoys. I'm not sure how to interpret these calls but I assume these are spurious and should not be considered in the analysis. However, my concern is if I filter out decoys in the bam before running Sniffles then those translocations would instead be mapped to real chromosomes, possibly increasing the false positive rate. Any thoughts on using decoys?

In the Nature Methods paper you present SV calling evaluations for Sniffles+NGMLR and Sniffles+BWA. Are there any known biases with regards to insertion, deletions, duplications, inversions and translocations when using Sniffles+minimap2 for nanopore reads?

**Comment by BioinformaticsBro** [comment]
@philres I've noticed that many of the SV calls are in regions of simple repeats. Since nanopore has a problem with these types of sequences, I'm guessing these are false positives. So I'm surprised you'd get such high precision rates, or do you do you filter these out?

**Comment by fritzsedlazeck** [comment]
Hey,
so about the alt contigs. Just ignore calls to these locations. You can also just map to the main chromosomes and this does not cause problems.

Sniffles + minimap2 and Sniffles + ngmlr work almost the same. There are some differences in certain regions where NGMLR looks better and produce a cleaner alignment. 

Yes the problem with the low complexity regions for ONT has been almost solved by the new basecaller. So, in this case, your assumption is correct that if you see deletions in low complexity regions they were almost always due to basecalling artifacts. With the newer basecaller (flipflop) we dont see that effect anymore.

I hope that helps
Fritz

**Comment by BioinformaticsBro** [comment]
Thanks @fritzsedlazeck 

What's the largest SNV in terms of MB one can expect to detect using minimap2 + sniffles + nanopore reads? What's your current record?

**Comment by fritzsedlazeck** [comment]
Well this is a bit hard. There is a drop in detection rate after 5kbp long insertions. For ngmlr sniffles communicate better with it. In this case we can report unresolved insertions that can be latger....
Deletions should not matter .
Does that help you?
Cheers
Fritz

**Comment by BioinformaticsBro** [comment]
@fritzsedlazeck That does, thanks!

**Comment by ggoodstudydaydayup** [comment]
Hi, 
    I have a small question about the Nanopore reads. 
    Did you correct or filter the Nanopore reads before mapping ?
    Thanks in advance.
Best wishes

**Comment by fritzsedlazeck** [comment]
No we usually take the raw ONT reads for mapping. I am always afraid that correcting them (self or with short reads) introduces biases against either haplotypes or other regions of the genome.
