### ISSUE TITLE
the vcf format problem!

### ISSUE THREAD

**Issue by Epigenetics-Wang** [fritzsedlazeck/Sniffles#141]
Hi,

thanks for sniffles, it appears to be nice, quick and flexible on my  data. I am having an issue with the VCF. In my vcf, I found there are so many sequences list in column 4 which stands for Ref. I am not sure about what kind of this type of variations. Some lines are  SVTYPE=INS, and some lines are  SVTYPE=DEL. Can you give me some advice ? Thanks

Sincerely!

**Comment by fritzsedlazeck** [comment]
Hi, 
thanks for reaching out. Every entry has an SVTYPE= that describes the event. 

So for an insertion (INS) the length of the sequence for the alternative column (5th) vs. the reference column (4th)  is larger, right? 

For deletions its the other way around since your sample misses some sequence compared to the reference. 

I hope that helps.
Fritz
