### ISSUE TITLE
Can I use Sniffles to call SV across different species?

### ISSUE THREAD

**Issue by qiuyixmm** [fritzsedlazeck/Sniffles#144]
For instance, can i use the long reads of chimpanzee to call SV against human genome using NGMLR-Sniffles pipeline? If so, it would affect the results of calling? Thanks!

**Comment by fritzsedlazeck** [comment]
Hi,
we never benchmarked this, but the core method of NGMLR would work to align these reads correctly. 
 Thus, the SVs calling will also work.  I would not be very concerned about the evolutionary distance since I would assume the distances from human to chimpanzee will be homozygous. 
The issue would be more in novel sequences in chimpanzee and how this would be represented. This would be a general problem for all mapping approaches. 

Cheers
Fritz
