### ISSUE TITLE
Adding short read support

### ISSUE THREAD

**Issue by jannafierst** [fritzsedlazeck/Sniffles#181]
I'm using Sniffles on ONT data and manually checking results results in several that are actually homopolymer errors. I am wondering if there is a way to also use Illumina reads in the context of Sniffles to eliminate these and focus on true SVs? Thanks!

**Comment by fritzsedlazeck** [comment]
Hi this is a problem with the ONT basecaller. A more recent basecaller has improved this a lot. If you have the possibility I would check this.  The problem is that the basecaller (Depending on the version) cannot handle homopolymers and thus shrinks them down to worst-case a bp. Which corresponds of course to deletions. We reported that in our paper.


The other way would be that you obtain a bed file with the homopolymer stretches and discard all the SV in these regions.  However, there can be variations compared to the reference genome. 

I hope that helps
Fritz

**Comment by jannafierst** [comment]
Okay thanks! If I set the parameters to ignore smaller SVs it seems to get rid of most of them, I was just exploring if there's a way to get the whole distribution without truncating. Sounds like it would have to be a combination of methods/reads.

**Comment by fritzsedlazeck** [comment]
yeah sorry. We saw still artifacts in between 8-12bp in homopolymers. Above 20 it looks good for the newest basecaller. 
Thanks for your feedback
Fritz
