### ISSUE TITLE
Option to avoid homopolymer indels 

### ISSUE THREAD

**Issue by cjain7** [fritzsedlazeck/Sniffles#194]
Hi,

Like the following parameter in sniffles:
`-l <int>,  --min_length <int>`

it would also be useful to support minimum compressed length parameter. Currently I see large number of simple sequences (e.g., AAAAAAAs) called as indels using ONT reads. Would be nice to have an option to suppress those.

Please let me know in case this is already supported. Thanks!

**Comment by fritzsedlazeck** [comment]
Dear @cjain7 ,
thanks for this suggestion. I would not want to do this, because these regions can also have real SV changes. However, I know these regions are also more often locations of base calling errors.. 
the other problem is the generalization across species. Are you suggesting to compute the entropy or so of this region to be able to filter them?

Thanks
Fritz

**Comment by cjain7** [comment]
Thanks Fritz. I guess my suggestion is provide an **optional** parameter exposed to users to suppress low-entropy calls. I do agree with you that these can filter out real SVs too. Therefore, the default can be set to not suppressing these.

I would assume an easy way to expose such an option would be "minimum HPC length". This could be 0 by default, but could be adjusted by user if needed.

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
