### ISSUE TITLE
vcf for a population

### ISSUE THREAD

**Issue by wangjiawen2013** [fritzsedlazeck/Sniffles#195]
Hello,
In the tutorial of calling structural variations(
https://github.com/fritzsedlazeck/Sniffles/wiki/SV-calling-for-a-population), vcf files across all samples were merged two times with survivor. I checked the difference between these two results with my datasets, they were almost the same, so why do we run it two times ?

**Comment by fritzsedlazeck** [comment]
The first stage is merging the de Novo calls. Here many of the samples might not have any information on a SV thus ./. as genotypes. The 2nd round tries to fill the gaps so that you know if a SV is not filled (./.) because it a) was just not called based on typical thresholds or b) the SV is indeed not present (0/0).  

I hope that clears this up
Thanks
Fritz
