### ISSUE TITLE
PacBio CCS minimap2 + sniffles versus ngmlr + sniffles

### ISSUE THREAD

**Issue by sjin09** [fritzsedlazeck/Sniffles#197]
Hello Fritz,

We have generated some human CCS data and we were wondering whether you have some done some benchmarking to compare the structural variation results from minimap2 BAM file and ngmlr BAM file and whether you have some recommendations.

I am aware that sniffles will work with minimap2 BAM files (provided that --cs flag is available).

Many thanks :D

Regards,
Sangjin

**Comment by fritzsedlazeck** [comment]
Dear @sjin09 ,
yes we did some comparisons also in the paper. the difference is not very huge. We see that some SV are more accurately captured from NGMLR. I also heard that a lot from other people at conferences. The problem is just that NGMLR is much slower than minimap2... 

Hopefully, that helps
Fritz
