### ISSUE TITLE
strandness

### ISSUE THREAD

**Issue by robinycfang** [fritzsedlazeck/Sniffles#201]
Hi Fritz,

I am using sniffles to call SV from tumor samples. I can't quite understand the STRANDS in vcf output, could you help me understand that?

`##INFO=<ID=STRANDS,Number=A,Type=String,Description="Strand orientation of the adjacency in BEDPE format (DEL:+-, DUP:-+, INV:++/--)">`
`chrM	1	0	N	<DUP>	.	PASS PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=chrM;END=16571;STD_quant_start=0.448849;STD_qu
ant_stop=0.320256;Kurtosis_quant_start=47.671302;Kurtosis_quant_stop=199.696049;SVTYPE=DUP;SUPTYPE=SR;SVLEN=16570;STRANDS=-+;RE=546;REF_stra
nd=0,0;AF=1	GT:DR:DV	1/1:0:546`
`chr1	142544647	892	N	<INV>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=chr1;END=143544523;STD_quant_start=0.0
00000;STD_quant_stop=0.591608;Kurtosis_quant_start=11.180571;Kurtosis_quant_stop=4.366498;SVTYPE=INV;SUPTYPE=SR;SVLEN=999876;STRANDS=++;RE=4
0;REF_strand=4,2;AF=0.869565	GT:DR:DV	1/1:6:40`

in the duplication example, the start breakpoint is - and end breakpoint is + strand? I don't know how to explain that. Thank you.

**Comment by fritzsedlazeck** [comment]
Sure. 
The strands give insights onto how the reads are mapping and thus how you could validate these SV. 
 A -+ indicates that for validation you need a primer 1 upstream of the start breakpoint and a primer 2 downstream of the end breakpoint. Only if the duplication exist you will get a product. 

Hope that helps
Fritz

**Comment by robinycfang** [comment]
Hi Fritz,

Thanks again for the reply. I am actually still wondering how to interpret duplication events. I understand that sniffles duplication refers to tandem deplication, but I am not sure how to read the genotype and AF information, such as followings:

`chr1	235573072	1583_0	N	<DUP>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=chr1;END=235573368;STD_quant_start=0.447214;STD_quant_stop=0.707107;Kurtosis_quant_start=1.710713;Kurtosis_quant_stop=5.873467;SVTYPE=DUP;SUPTYPE=SR;SVLEN=296;STRANDS=-+;RE=13;REF_strand=11,10;AF=0.382353	GT:DR:DV	0/1:21:13`
`chr1	158962195	1052	N	<DUP>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=chr1;END=158962913;STD_quant_start=7.007139;STD_quant_stop=2.302173;Kurtosis_quant_start=3.966455;Kurtosis_quant_stop=0.311409;SVTYPE=DUP;SUPTYPE=SR;SVLEN=718;STRANDS=-+;RE=14;REF_strand=17,18;AF=0.285714	GT:DR:DV	0/0:35:14`
`chr2	3184170	1977_1	N	<DUP>	.	PASS	IMPRECISE;SVMETHOD=Snifflesv1.0.11;CHR2=chr2;END=3185251;STD_quant_start=1.712698;STD_quant_stop=35.788266;Kurtosis_quant_start=10.981890;Kurtosis_quant_stop=-1.106989;SVTYPE=DUP;SUPTYPE=SR;SVLEN=1081;STRANDS=-+;RE=31;REF_strand=4,3;AF=0.815789	GT:DR:DV	1/1:7:31`

The first line looks fine and it looks like a heterozygous, with 21 normal reads and 13 variant reads. The second genotype (0/0) looks a bit weird to me, why do you still call it a variation when both locations are normal? The third one (1/1) seems to have all reads with tandem duplication, but why each has their own specific variant reads (i.e., 7 and 31, respecitvely)?

**Comment by fritzsedlazeck** [comment]
Dear @robinycfang ,

The number of reads supporting (RE) depends on multiple factors. a) coverage at the region, b) if the reads indicating an event passes several filter criteria (MQ, overall alignment identity, not too often split etc.)

So as you said the first one indicates as het event meaning only one haplotype has likely a tandem duplication. The 3rd one as homozygous meaning likely both haplotypes have the tandem duplication. 

The 2nd one: We did not find that many reads to infere its heterozygous based on the default settings. As you can see 29% of the reads are indicating this event, but 30% would be needed to label it as heterozygous. Looking at it I think it will be fair to assume it is heterozygous... 

For the coordinates: The entries would show that e.g. B is duplicated as a variant, thus would mean ABBC and both B. The END would be indicated at the end of the first B. This is since we reflect the reference coordinate system and not your sample.  I hope that makes sense. So Start - END coordinates is the entrie region that is tandem duplicated in your sample. 

Hope that helps
Fritz

**Comment by robinycfang** [comment]
Thanks for your reply, Frizt. That works!
