### ISSUE TITLE
survivor merge: keep all the samples

### ISSUE THREAD

**Issue by Emily072020** [fritzsedlazeck/Sniffles#207]
I have two samples (two columns following the column "FORMAT" in vcf files).

By using the command: 
SURVIVOR merge files.txt 1000 2 1 1 0 0 merged.vcf

in the result: "merged.vcf", there is only one sample kept. 

Is it possible that two samples can be kept in the result "merged.vcf"? 

Thanks a lot.

**Comment by fritzsedlazeck** [comment]
so you are merging a premerged vcf files ? 
No sorry this is not possible at the moment, for various reasons. 
You could work around this to split up your input files before the complete merge.

I hope that helps
Fritz

**Comment by Emily072020** [comment]
Hi thanks,

No. I am merging 3 vcf files from 3 different tools, which were listed in a file called "files.txt".
Each vcf file is like:
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  **Sample_control  Sample_tumor**

By using the command:
SURVIVOR merge files.txt 1000 2 1 1 0 0 merged.vcf

in the result: "merged.vcf", there is only one sample kept, which I mean:
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  **Sample_control  Sample_control_1 Sample_control_2**
without information of  **Sample_tumor**.

I want to further filter the merged file "merged.vcf" to separate Germline and Somatic SVs, so I wish information of Sample_control and  Sample_tumor be both kept. 

Thanks again.

**Comment by fritzsedlazeck** [comment]
Ah I see. 

Yeah sorry, that's not directly possible right now. 
If I were you:
1. Filter the VCF files that you obtained from the tools to have only tumor SV calls left. (you could either split these VCF files up (e.g. bcftools view -s sample_name (if I am right), or use awk etc. )
2. Merge then using SURVIVOR merge. 

You see the problem is that I designed SURVIVOR for using multiple tools per sample and then be able to further merge across samples. Thus, SURVIVOR only takes the name of the first sample column. 
Thanks
Fritz

**Comment by Emily072020** [comment]
Hi Fritz,
Clear. Thank you very much for your help.

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
