### ISSUE TITLE
What does the "STRANDBIAS" tag mean?

### ISSUE THREAD

**Issue by shig913** [fritzsedlazeck/Sniffles#234]
Hi,
I had a vcf file with some SVs, but some SVs were tagged as "STRANDBIAS".
What does the "STRANDBIAS" tag mean?

Thanks

**Comment by ddrichel** [comment]
If the sum of reads mapping to both strands is >5, a Fisher exact test is conducted to test for even distribution of reads to strands.
FILTER is set to "STRANDBIAS" if p<0.01.
This indicates possible problems with the quality of the variant, however be careful since the p-value is very strict and false positives are expected, for details see: https://github.com/fritzsedlazeck/Sniffles/issues/209

**Comment by shig913** [comment]
I understand it.
Thanks for kind reply!

**Comment by ddrichel** [comment]
@fritzsedlazeck resolved

**Comment by fritzsedlazeck** [comment]
Thanks, @ddrichel makes it easy :)
