### ISSUE TITLE
Positions of SVs (insertions)

### ISSUE THREAD

**Issue by MehmetGoktay** [fritzsedlazeck/Sniffles#24]
Hi Fritz, 

I m willing to compare SVs which were called by sniffles with pacbio and short read read caller. (I use pindel for that).

Everything worked pretty well, there is one thing that I do not understand. The way that you give positions for indels.

For example for pindel it is always one nucleotide difference between start and stop of sv. Even if it is a SNP or 100 nucleotide insertions
.
But for Sniffles it varies a lot. I didnt understand the logic behind it. That is why currently I can not compare these two tools' output for indels.

Is it possible to tell me why insertion positions varies that much?  Are those complex indels or what?

For example this one;
NC_003075.7	**7231255**	7968	N	<INS>	.	PASS	PRECISE;SVMETHOD=Snifflesv1.0.6;CHR2=NC_003075.7;END=**7231260**;STD_quant_start=0.000000;STD_quant_stop=1.140175;Kurtosis_quant_start=17.144694;Kurtosis_quant_stop=12.218618;SVTYPE=INS;SUPTYPE=AL;SVLEN=11;STRANDS=+-;RE=21	GT:DR:DV	./.:.:21

There is 5 nucleotides distance between start and stop position. I believe it should be something like that start:**7231255** and stop **7231256** 

Best,
Mehmet

**Comment by fritzsedlazeck** [comment]
Hi Mehmet,
the positions of the SV are sometimes not precisely enough to pinpoint to one bp (eg. higher error rates or low complexity region...) . Sniffles gives the most supported start and the most supported stop position based on every read. This means within these 5bp there is an insertion of 11bp. Other methods do the same e.g. Manta from illumina.  

If you have troubles to compare those sites because of this you could check out SURVIVOR (option 5) which compares SV across multiple vcf files and can take these wobbles into account. [https://github.com/fritzsedlazeck/SURVIVOR](https://github.com/fritzsedlazeck/SURVIVOR)

Cheers
Fritz

**Comment by MehmetGoktay** [comment]
Thank you very much Fritz!.

**Comment by fritzsedlazeck** [comment]
You are  welcome. Let me know if there is anything else looking strange. Feedback is always welcome!
Thanks
Fritz
