### ISSUE TITLE
the recommended sequencing depth

### ISSUE THREAD

**Issue by charliechen912ilovbash** [fritzsedlazeck/Sniffles#246]
Hi,

I am wondering about the recommended sequencing depth for Sniffles to detect correct SV.

**Comment by fritzsedlazeck** [comment]
We benchmarked it in the manuscript (12x + in human)... but I am sure you can go a bit lower. It depends on poliploidy and how important are het variants.. I think you can get away with 8x ..

**Comment by charliechen912ilovbash** [comment]
I see, thanks for answering!

**Comment by fritzsedlazeck** [comment]
Sorry for the late reply.. Figure 6 shows this downsampling process. 

We have also checked for lower coverages and made improvements. Its always hard to pinpoint an exact coverage since the coverage is a Poisson distribution and depending of the variants are more heterozygous or not... 

Hope that helps. 
Fritz

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
