### ISSUE TITLE
Filter column in VCF sometimes contains 'GT'

### ISSUE THREAD

**Issue by SAMtoBAM** [fritzsedlazeck/Sniffles#289]
Everything is said in the title essentially.
Does not appear specific to any type of SV (e.g. INS or IMPRECISE or 0/0 etc)

That's it, tiny bug.

**Comment by smolkmo** [comment]
Hello,

this is actually due to the genotype filter, which will flag SVs where the likelihood of a 0/0 genotype (in relation to the called genotype) is higher than the filtering threshold - indicating Sniffles2 cannot be sure whether to call for the reference or not. Depending on your application, you may wish to include/exclude calls that have a GT filter tag.

Best regards,
Moritz

**Comment by SAMtoBAM** [comment]
I am not sure I understand sorry
This GT tag in the filter column appears in calls with 0/0, 0/1 and 1/1 genotypes.

**Comment by smolkmo** [comment]
That is expected because even when Sniffles calls an SV 0/1 or in rare cases 1/1, the quality of the genotype may be low - triggering the GT filter tag. This may be the case e.g. in low-coverage regions or when the observed relative read support deviates from what is expected for the actually called genotype by too much.

**Comment by SAMtoBAM** [comment]
Ok, I understand now that it indicates issues for any genotype call, not just 0/0.
Thanks for the explanation!
