### ISSUE TITLE
"None" value in COVERAGE leads to an error with pyvcf

### ISSUE THREAD

**Issue by andyjslee** [fritzsedlazeck/Sniffles#337]
There are cases where Sniffles2 reports some of the "COVERAGE" field as "None" (e.g. "None,None,100,None,None"). As a result, reading a Sniffles2 VCF file using pyvcf throws the following error: ValueError: could not convert string to float: 'None'. The issue goes away if I change the header from:

`##INFO=<ID=COVERAGE,Number=.,Type=Float,Description="Coverages near upstream, start, center, end, downstream of structural variation">
`

to

`##INFO=<ID=COVERAGE,Number=.,Type=String,Description="Coverages near upstream, start, center, end, downstream of structural variation">
`

**Comment by wdecoster** [comment]
I have opened a PR that should fix this issue. My fix avoids reporting None as the coverage and uses -1 instead if the value is None/unavailable.

Note that I'm not sure if the coverage being None is actually a deeper problem somewhere else that we should look into, but at least this gets the reporting done...

@fritzsedlazeck @lfpaulin

**Comment by chapplec** [comment]
@wdecoster this wasn't fixed in the end, right? I found [your PR ](https://github.com/fritzsedlazeck/Sniffles/pull/338) but I see it is closed and the [relevant code](https://github.com/fritzsedlazeck/Sniffles/pull/338/commits/b07f0a731d0babcf16565534f32abb711a2911de#diff-b27983d910b71a188d59a175f96891bc71b325a5ee0b00577a1a3fc625abb144R137) hasn't been added to the  `src/sniffles/vcf.py` I see on master. 

Am I missing something? Can I find it somewhere else?

This bug is a problem since it means that Sniffles is producing VCFs that don't conform with the standard so various downstream processing tools will fail. I am hitting this bug in a production system because a client of mine is using Sniffles so my system rejects the malformed VCF. 

I can simply change all `None` to `0` (why did you go for -1 instead, by the way?) manually but this really should be fixed in the source.

**Comment by wdecoster** [comment]
No idea why it is closed to be honest - but it seems you are right this wasn't fixed.
I went for `-1` because it is valid, and clearly differentiates it from `0`, which is also valid. I don't know the source of those things being `None` and I don't want to make any assumption of what `None` means, so -1` means `unexpected value` for me. It is a clear flag that something is wrong here, while staying compliant with the specifications.

If the developer(s) can decide that None actually should be 0 (I didn't check the logic) then 0 is just fine.

**Comment by chapplec** [comment]
Hmm, yes, that can make sense @wdecoster. I think it's probably a fair assumption that `None` means `0` but I also understand your reluctance to make any assumption, fair or not. I'll now have to check if my system will accept -1 as valid, I have no idea. On the one hand, it is indeed a float, but on the other it makes no biological sense to have negative coverage.
