### ISSUE TITLE
REF allele is N for all SV types

### ISSUE THREAD

**Issue by weilu1998** [fritzsedlazeck/Sniffles#374]
Hi, 

I used Sniffles2 to generate a VCF file from 3 samples with ONT reads. When I look at the REF allele column, I found that they are all represented by N. I am wondering is there a particular reason for that? I am planning to used the VCF for other short-reads based genotyping software and the Ns in REF column will cause a lot of trouble.

Thanks,
Wei

**Comment by yangxin-9** [comment]
I have the same problem have you solved it yet?

**Comment by yangxin-9** [comment]
Thanks so much for response.

**Comment by bbimber** [comment]
Hello - is this still the expected behavior (listing N as the REF), in sniffles 2.5?

**Comment by fritzsedlazeck** [comment]
Yes. You need to provide a reference file to sniffles. Otherwise it's N .
Cheers
Fritz

**Comment by bbimber** [comment]
@fritzsedlazeck: that's kind of what i was assuming, but we ran the per-sample sniffles command and the joint/merge command with --reference. I'll look at this some more to confirm.

**Comment by bbimber** [comment]
@fritzsedlazeck: I repeated this to verify that I included --reference for both SNF generation and merging, and I got the same result: Ns are listed as REF for everything. 

I am using a CRAM as the input, not a BAM. Could this be the issue? This isnt exactly the same issue: #440; however, CRAM/BAM might behave differently as far as finding the ref bases? 

I'm at a loss to explain this otherwise. Happy to share log files.
