### ISSUE TITLE
Changing --minsvlen value affects variant calling globally in an unexpected manner

### ISSUE THREAD

**Issue by hoyonh** [fritzsedlazeck/Sniffles#381]
Changing the --minsvlen value with sniffles leads to strange changes in the output. See below for a snippet of a set of outputs with three different --minsvlen values -- using the same BAM input file.

--minsvlen 30 ---> 603 DEL of -34 to -30 bp (269 with GT = 1/1)
--minsvlen 20 ---> 685 DEL of -34 to -30 bp (276 with GT = 1/1)
--minsvlen 10 ---> 390 DEL of -34 to -30 bp (211 with GT = 1/1)

Changes in the number of indels are seen also with indels of other ranges of sizes. I saw this with 1 ONT data, 1 PacBio HIFI data, and 2 PacBio 1st gen data.

It looks to me that changing the minsvlen value changes the likelihood of variant calling globally - rather than simply identifying additional variants of smaller sizes. Is this intentional? It seems weird. I did not see anything in the papers suggesting that this is a part of the design.

I am using sniffles (2.0.7) with BAM files made with minimap2 (2.17) or pbmm2 (1.10.0).

**Comment by fritzsedlazeck** [comment]
Thanks for testing this.
It might be because we use it for limiting the scanning on the alignment events . So some noisy regions might be impacted by the number of detected reads that support the Sv.. 
Given it's in these size regimes i think it's interesting and confusing but not really a bug i think.. we recommend not to go below 30. Above i would think this behavior should change. 

Thanks for reporting it, certainly interesting!
Fritz

**Comment by hoyonh** [comment]
No problem. I actually liked the output with -minsvlen 20. Many called indels looked real - quite nice with ONT and pretty good with PacBio HIFI data I used. I expect that first-gen PacBio would not be good, but first-gen PacBio is first-gen PacBio... I am closing this.

**Comment by fritzsedlazeck** [comment]
Yeah we would need to add some features/ cross checks to make it work further down the variant size .
Thanks
Fritz
