### ISSUE TITLE
How to filter the variants called by sniffles

### ISSUE THREAD

**Issue by CVan19** [fritzsedlazeck/Sniffles#40]
Hi,  I've just run sniffles to call structral variants with pacbio data. Now I want to filter some variants which look like impossilbe. For example,
```
1       724782  0       N       <DUP>   .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.7;CHR2=1;END=224202044;ZMW=19;STD_quant_start=59.084034;STD_quant_stop=93.640885;Kurtosis_quant_start=-1.482464;Kurtosis_quant_stop=-1.658414;SVTYPE=DUP;SUPTYPE=SR;SVLEN=223477262;STRANDS=-+;RE=26    GT:DR:DV        ./.:.:26
```
The length of this SV is 223477262, almost equal to the length of chromesome 1. And in the INFO field it is marked as IMPRECISE. I wonder whether I can use this mark to exclude it ? If not , is there any other way to filter raw variants?

**Comment by fritzsedlazeck** [comment]
Hi,
so one thing would be to filter for Precise instead of IMPRECISE. This reflects the agreement of the individual reads. If you want to have more control use the STD_quant flags for start and stop that gives you more insights. Sniffles is using these STD values already to prefilter the results, but you can make it more constrain if you like. It often depends on the technology and sample at hand.

Another thing would be to filter for the number of read supports (RE=) or if you run --genotype the allele frequency. 

I hope that helps
Fritz

**Comment by CVan19** [comment]
Thank you for your reply, and your advice really helps me. But I still have one question, what is the meaning of "filter for Precise instead of IMPRECISE". Can I interpret  that as meaning that I should just discard varaitns marked as IMPRECISE,and only filter those variants marked as PRECISE?

**Comment by fritzsedlazeck** [comment]
So just to make it clear. Sniffles has already an automatic filter in the output. 

If you want to filter further, the easiest is to ignore the IMPRECISE marked calls or you use the allele frequencies.

Cheers
Fritz

**Comment by CVan19** [comment]
I see what you mean. Thank you very much!
