### ISSUE TITLE
questions about the detection of intra-chromosomal translocation

### ISSUE THREAD

**Issue by FrankFeng** [fritzsedlazeck/Sniffles#42]
1. Can Sniffles call intra-chromosomal translocation from Pacbio long read data?

2. When an intra-chromosomal translocation is well supported by the long read data (e.g. with strong evidence of split alignments), does Sniffles report it as a `<DEL>` or `<TRA>` ? It looks to me that Sniffles calls it as `<DEL>` rather than as `<TRA>`, because Sniffles doesn't check the depth of coverage to rule out the case of deletion?

Thank you!

**Comment by fritzsedlazeck** [comment]
1. No we cannot distinguish  between DEL/INV or intra-chromosomal translocations. The signal are actually identical. Let me know if you find a caller that can do that. I would be interested to see how. The only way you may be able to is to filter for very large events. 

2. Yes we dont use the coverage to determine the type. You can filter/ post process this information as it is given in the vcf file. (use --genotype)

I hope that helps.
Fritz

**Comment by FrankFeng** [comment]
Thanks Fritz!

**Comment by FrankFeng** [comment]
Hi Fritz,

Can Sniffles distinguish between large tandem duplication (DUP) and intra-chromosomal translocation? 

I am looking at Sniffles' structural variant calls now. It looks to me that an extremely large DUP called by Sniffles can also be interpreted as an intra-chromosomal translocation. Can Sniffles distinguish between those two types of SVs? 

Thanks.

**Comment by fritzsedlazeck** [comment]
Hi Frank,
Sniffles cannot detect/call intra-chromosomal translocations as such. Thus, it reports the variants as often (very) large DEL, DUP, INV. So in that perspective I would look at SVs that are very large to be likely large intra-chromosomal translocations. 

I looked at this over some simulated data and the signals are identical. So the only thing that I tested out is to use a distance threshold of the breakpoints, but that is very unsatisfying because it can be in some organism that there is a large e.g. inversion. Thus, I left it as it is right now. 

I hope that helps.
Fritz
