### ISSUE TITLE
How to distinguish tandem repeats in Sniffles VCF?

### ISSUE THREAD

**Issue by tnguyengel** [fritzsedlazeck/Sniffles#428]
Does Sniffles annotate tandem repeats in resulting VCFs when the sniffles is invoked with 
`--tandem-repeats [bed file with tandem repeat regions]` ?

I.e.  does Sniffles annotate anything special in the VCF like motif size, number of repeats, or the fact that this is a region from the tandem-repeats annotation bed?

If tandem repeats are simply annotated as a duplication (DUP) in the VCF with no additional tandem-repeat-specific annotation, how much would the number of repeats in the sample have to differ from the reference genome in order to be called?

**Comment by ymcki** [comment]
My understanding is that all DUPs called by sniffles are tandem repeats that are exactly one repeat more than the reference. As long as the size of the tandem repeat is >= minsvlen (default 50), it will be outputted. If the tandem repeat has more than one copy relative to the reference, it will always get called as an INS.

On the other hand, interspersed repeats are always called as INS in sniffles.

**Comment by fritzsedlazeck** [comment]
Sorry no. so that file is just so the merge of SV candidates (internally) are more relaxed in tandem repeat regions. 

Tandem repeat are not duplications!  Sniffles reports duplciations independent of the copy number of the region. Insertions are novel sequence element inserted in a region. Mappers can confuse small tandem duplciations (not tandem repeats) as insertions and then Sniffles interprets that signal. 

I hope that clears this up a bit.
Thanks
Fritz

**Comment by ymcki** [comment]
> Sorry no. so that file is just so the merge of SV candidates (internally) are more relaxed in tandem repeat regions.
> 
> Tandem repeat are not duplications! Sniffles reports duplciations independent of the copy number of the region. Insertions are novel sequence element inserted in a region. Mappers can confuse small tandem duplciations (not tandem repeats) as insertions and then Sniffles interprets that signal.
> 
> I hope that clears this up a bit. Thanks Fritz

Thanks for your reply. 

My understanding is that duplication/repeat is by definition that a genomic region that has more than one copy. Tandem repeats are duplications that are sitting next to each other exactly. If duplications are not next to each other, they are called interspersed repeats. 

This is an example of a single copy tandem repeat of HG002 called by sniffles2.2
chr10   79745428        Sniffles2.DUP.2402S9    N       <DUP>   47      PASS    PRECISE;SVTYPE=DUP;SVLEN=106988;END=79852416;SUPPORT=12;COVERAGE=27,27,62,27,25;STRAND=+-;AF=0.33
3;STDEV_LEN=0.000;STDEV_POS=0.000       GT:GQ:DR:DV     0/1:53:24:12

This is an example of a three copies (99bp repeat unit in PLIN4 gene) tandem repeat of HG002 called by sniffles2.2 as insertion
chr19   4511726 Sniffles2.INS.155S12    N       TTGGCCACATTCGCAGCACCGGTCACCCCACTGCCAAGGGTGTTCTTTGTACCTGTTGCGATATTTTGGGTCGTTTTCAGCCCAGTTTGCACAGCACCCTTGGCCACGTTCACAGCACCGGTGACCCCACTGCAGACAGTGTCCTTGGTACCGGTCAGCACGGTCTTGGCCGTGTCTACACCCGTCTGGACGGCCCCC   60      PASS    PRECISE;SVTYPE=INS;SVLEN=198;END=4511726;SUPPORT=29;COVERAGE=44,43,43,41,44;STRAND=+-;AF=
0.674;STDEV_LEN=0.352;STDEV_POS=0.000;SUPPORT_LONG=0    GT:GQ:DR:DV     0/1:59:14:29

This is an example of an interspersed repeat of inserting LINE-1 element from ADGRL3 gene (chr4:61939924-619459601) to NRCAM gene observed in HG002. Sniffles 2.2 calls it as an insertion in NRCAM gene. While you can see the read coverage doubled also at ADGRL3 chr4:61939924-619459601 but it is not called as DUP.
chr7    108188805       Sniffles2.INS.AECS6     N       <INS>     59      PASS    PRECISE;SVTYPE=INS;SVLEN=6069;END=108188805;SUPPO
RT=31;COVERAGE=41,34,34,34,58;STRAND=+-;AF=1.000;STDEV_LEN=1.483;STDEV_POS=0.000;SUPPORT_LONG=0 GT:GQ:DR:DV     1/1:60:0:76

I reached my conclusion from these examples that DUP is only called for tandem repeat with exactly one more copy than reference. Are there other situation that a DUP will be called instead of an INS?

**Comment by fritzsedlazeck** [comment]
I think you are mixing maybe tandem repeats from tandem duplciations. They are to some point related. 

Depending on the region and the allele it can be reported as INS or DUP . That is depending a bit on the size of the allele and how the aligner sees the event. 

So yes DUP is only a tandem duplciation , in theory it cna be more than one copy.. 
INS can be novel element or a very small tandem DUP (e.g. STR expansion).
I hoe that helps. 
Closing this as you came to the right conclusion I think. 
Thanks
Fritz
