### ISSUE TITLE
Here are some question

### ISSUE THREAD

**Issue by anduin0909** [fritzsedlazeck/Sniffles#435]

**Comment by anduin0909** [comment]
I am a college student majoring in agriculture.I encountered some issues while running Sniffles.
Is the file output by ngmlr a bam file? Why is my sniffles unable to operate on the output file? If the output is a sam file, how can I change it to bam? I have tried the samtools change method, but always report errors, display read errors, and close errors.Could you please help me answer this question? It has been bothering me for a week now.

**Comment by fritzsedlazeck** [comment]
Sorry @anduin0909 for the delay. 
So 1. you need to generate a sorted bam file. We typically use samtools for this (view + sort options) . 
2. Take the sorted and indexed bam file then as input for Sniffles. 
That should do it. 
Hope that helps. I am closing this issue because there are many tutorials out there, but feel free to comment if you get lost. 
Fritz
