### ISSUE TITLE
Discrepancies between sniffle 2.0.7 and sniffle 2.2

### ISSUE THREAD

**Issue by mhjiang97** [fritzsedlazeck/Sniffles#445]
Hi!

I have a patient sample with a known gene fusion/genomic translocation (i.e. PAX5::ETV6).
Sniffle 2.0.7 did call this BND in the vcf by running `sniffles --input mysample.bam --vcf out.vcf --non-germline --reference hg38.fa --tandem-repeats human_GRCh38_no_alt_analysis_set.trf.bed`:
```
chr12  11824930        Sniffles2.BND.4C95S4    N       N]chr9:37002649]        60      PASS    PRECISE;SVTYPE=BND;SUPPORT=13;COVERAGE=18,18,40,38,37;STRAND=+-;NM=0.046;AF=0.406;CHR2=chr9;STDEV_POS=0.000 GT:GQ:DR:DV     0/1:60:19:13
chr9   37002650        Sniffles2.BND.4111S3A   N       N]chr12:11824929]       60      PASS    PRECISE;SVTYPE=BND;SUPPORT=14;COVERAGE=18,19,38,35,34;STRAND=+-;NM=0.048;AF=0.452;CHR2=chr12;STDEV_POS=2.504   GT:GQ:DR:DV     0/1:60:17:14
```
However, I cannot get similar results from Sniffles 2.2 by running:
`sniffles --input mysample.bam --vcf out.vcf --mosaic --sample-id mysample --mosaic-af-max 0.5 --mosaic-af-min 0.01 --reference hg38.fa --tandem-repeats human_GRCh38_no_alt_analysis_set.trf.bed --mosaic-include-germline`
In addition, I also tried to add the following flags but still got no BND indicating the known translocation: `--bnd-min-split-length 500`, `--qc-bnd-filter-strand False`, `--bnd-min-split-length 1`, `--cluster-merge-bnd 1500`

Could you please advise me how to make sure the results of Sniffles 2.2 reliable? THANKS IN ADVANCE!

Best regards,
Minghao

**Comment by fritzsedlazeck** [comment]
I think a potential issue is that --mosaic tag.  We refined parameters for --mosaic to only report SV with VAF 5-20%. So what you want to do is leading the --mosaic tag out since I see you have a heterozygous variant. 
I hope that makes sense .  We are trying to make this more obvious and integrated , but for now mosaic and default mode address 5-20% VAF and 20+% VAF , respectively. 
If you ever want to debug on sniffles use --no-qc which writes out all the candidates. 
Thanks
Fritz

**Comment by eesiribloom** [comment]
if @mhjiang97 is using the --mosaic-include-germline tag will sniffles not report both SVs with AF 5-20% AND >20% ?

**Comment by lfpaulin** [comment]
Yes, however we have received some reports that sometimes variants are missing, if that is the case for you please let us know
