### ISSUE TITLE
What is COV_CHANGE_FRAC

### ISSUE THREAD

**Issue by weishwu** [fritzsedlazeck/Sniffles#454]
Some of my ground truth SVs were marked as COV_CHANGE_FRAC which is explained as "Coverage fractional change filter" in the header. What does this mean?

**Comment by fritzsedlazeck** [comment]
Sniffles has currently a filter in that checks coverage level across the entire SV. We are working on refining this because its too conservative right now. There is a parameter for deletion for this.. but not INV etc. 
So yeah we need to tune this threshold further so I thikn its ok to ignore this flag.. especially if its longer SV. 
Hope that helps
Fritz

**Comment by weishwu** [comment]
Thanks!

**Comment by weishwu** [comment]
@fritzsedlazeck 
Sorry to reopen this. Are there any other filter flags that I should pay attention to?
