### ISSUE TITLE
how sniffles reflect Cell heterogeneity

### ISSUE THREAD

**Issue by Davidseye** [fritzsedlazeck/Sniffles#467]
when many cells have  different sv in the same loci ,those support reads support the different sv  .sniffles will show all sv or just the main sv?  Will the vaf of the sv represent the  heterogeneity precisely?  Hoping for your reply!

**Comment by fritzsedlazeck** [comment]
Thanks @Davidseye 
so that depends a bit.. if you have a cell mix and expect low frequency SV (below 20% VAF in the sample) then you need to run mosaic mode.  That by default reports down to 5% of the reads or at least 2 reads support.  You can alter this behaviour e.g. when you have more coverage since this is the most impacting factor for your detection. 

Hope that helps
Fritz

**Comment by fritzsedlazeck** [comment]
Just to add, it also depends on how similar the SV are across the cells because we are doing a clustering step on the per read signal.. So if the SV are very similar it will be grouped together and reported as one SV. If the two or more SV are different enough then it will be separate entries. 
Thanks
Fritz

**Comment by Davidseye** [comment]
thanks a lot .&nbsp; maybe there is a way to calculate the clonal and subclonal&nbsp; frequency of sv&nbsp; &nbsp;? can i use it to construct a&nbsp;&nbsp;phylogenetic tree



---Original---
From: "Fritz ***@***.***&gt;
Date: Mon, Apr 22, 2024 21:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [fritzsedlazeck/Sniffles] how sniffles reflect Cell heterogeneity(Issue #467)




 
Just to add, it also depends on how similar the SV are across the cells because we are doing a clustering step on the per read signal.. So if the SV are very similar it will be grouped together and reported as one SV. If the two or more SV are different enough then it will be separate entries.
 Thanks
 Fritz
