### ISSUE TITLE
Overcalling during force calling

### ISSUE THREAD

**Issue by czakarian** [fritzsedlazeck/Sniffles#481]
Hi Fritz,

I've been using the sniffles force calling method to regenotype SVs and it seems like I'm running into some issues of overcalling. 

To make sure, I ran 1. sniffles regular, 2. sniffles force calling, and 3. cutesv force calling on the same sample and compared the genotype counts of each (shown below). The sniffles and cutesv force calling runs both used the same input vcf.

Command used for sniffles force calling
`sniffles --input $bam --genotype-vcf $in_vcf --vcf $out_vcf -t $n --tandem-repeats $tandem_bed --reference $ref 
`

```
## Sniffles regular (27655 SVs)
    170 ./.
   2109 0/0
  18102 0/1
   9553 1/1

## Sniffles force calling (35371 SVs)
    355 ./.
  77970 0/0
  22691 0/1
  12680 1/1

## cuteSV force calling (25260 SVs)
  88436 0/0
  17088 0/1
   8172 1/1
```
I was able to look at other samples as well and sniffles force calling was consistently reporting between 30,000-36,000 SVs per sample, which is higher than expected. I tried looking at some bams to assess individual SV calls, but figured you might have a better sense of what might be happening. I'd really appreciate any insight!

Best,
Christina

**Comment by lfpaulin** [comment]
Hi Christina,

It looks like an odd behavior. A couple of questions 
- Which version of Sniffles are you using?
- How many SVs are in the input VCF?

Best
Luis

**Comment by czakarian** [comment]
Hi Luis,

I've tested force calling with Sniffles v2.2 and v2.3.3 on the same sample and got the same outcome with both (identical counts). The input VCF I'm using is a merged SV callset and has 113696 total SVs. I reformat the input VCF to only retain the first 'SAMPLE' column before providing it as input (by removing columns 11 and greater). The sample column that is left does have some GT information for certain SVs leftover, not sure if that matters.  

Best,
Christina

**Comment by lfpaulin** [comment]
Hi Christina,

Sniffles genotyper (cuteSV too) will take all the SVs in the "genoype" input (`--genotype-vcf`), in your case 113,696 SVs, and will assess them in the input sample. As you can see bellow the total SVs is the force calling experiments is in fact 113,696. Importantly, the genotyper may call SVs that were missed by the regular call. I think your numbers are the sum of HET and ALT SVs, moreover for sniffles the 0/0 genotype can be given when the VAF is below sow threshold.
If you refer to having 113,696 SVs in every force-calling / genotyped file, that is by design
If you refer to having 35,371 SVs in Sniffles force-calling / genotyped file, that is also expected as some SVs may be missed during regular call and detected during genotyping/force-calling. 

```
Sniffles call	
170	./.
2109	0/0
18102	0/1
9553	1/1
29934	Sum
	
Sniffles force	
355	./.
77970	0/0
22691	0/1
12680	1/1
113696	Sum
	
CuteSV force	
88436	0/0
17088	0/1
8172	1/1
113696	Sum
```
