### ISSUE TITLE
How to turn off joint genotyping in multisample calling

### ISSUE THREAD

**Issue by tnguyengel** [fritzsedlazeck/Sniffles#487]
What parameters should we use if we want the genotypes in the single-sample call to match the genotypes from the multi-sample calls?

EG)
- single sample: site=HOM_REF with strong support --> multisample:  site = HOM_REF for that sample
- single sample: site = HET/HOM_ALT with strong support --> multisample:  site = HET/HOM_ALT for that sample
- single sample: site = variant might exist but fails QC --> multisample:  site = missing for that sample

Would these parameters be sufficient?

Sniffles per-sample calling:
```
sniffles \
        -i [in_bam] \
        -v [out_vcf] \
        --snf [out_snf] \
        --sample-id [sample_id] \
        --output-rnames \
        --qc-output-all
```

Sniffles multisample calling:

```
sniffles \
        --input [snf_sample_id_tsv] \
        --vcf [out_merged_vcf] \
        --combine-high-confidence 0 \
        --combine-low-confidence 1.1 \
        --combine-low-confidence-abs [total samples + 1]  \
        --combine-null-min-coverage 1

```

**Comment by lfpaulin** [comment]
Hi @tnguyengel 
The results from the single sample and multi-sample call for individual X should be very similar but not identical
based on your comment

> single sample: site=HOM_REF with strong support --> multisample: site = HOM_REF for that sample

This one should be the same if the number of reads detected for the variant in sample X is zero otherwise it goes to point three

> single sample: site = HET/HOM_ALT with strong support --> multisample: site = HET/HOM_ALT for that sample

This one would be tricky, because the multi-sample calling will "rescue" some variants that have low support (i.e 5 reads 3 REF 2 ALT GT HET if the average coverage is ~30x) that may be removed from single sample calling but genotyped and show as present in multi-sample calling. This effect is by design 

> single sample: site = variant might exist but fails QC --> multisample: site = missing for that sample

Here are the SVs that are "rescued" in multi-sample calling, the genotypes will vary

Now regarding the four `combine` parameters you show:

`--combine-high-confidence` is unchanged
default=0.0  yours=0

`--combine-low-confidence` is changed so more SV will reported, as it is a fraction 1.0 would be the max
default=0.2  yours=1.1

`--combine-low-confidence-abs` same as above you select N+1
default=2  yours=N+1

`--combine-null-min-coverage`
Here more SVs will be "rescued" and genotyped, below 5 the GT is ./., but now it acts fro one read
default=5  yours=1

I hope this answer your questions

Best
Luis
