### ISSUE TITLE
Genotyping for homozygous sample

### ISSUE THREAD

**Issue by MehmetGoktay** [fritzsedlazeck/Sniffles#49]
Hi Fritz,

I work with Arabidopsis thaliana which we dont expect to see so much heterozygosity. But Half of my SV calls basically heterozygous and I dont want to filter them out. 

Is there any parameter that I can use for genotyping considering this problem?

I have found these but I dont know which I am supposed to use: 

-f <float>,  --allelefreq <float>
--min_het_af <float>
--min_homo_af <float>

Best Regards,
Mehmet

**Comment by fritzsedlazeck** [comment]
Hi Mehmet,
do you mean because its an inbred line?

so -f 0.8 will filter out all SV with an allele frequency lower than 80%. 
--min_het_af --min_homo_af can be only used to influence the genotype prediction.

I would encourage you to look at some regions where heterozygous SVs are reported over e.g. IGV. 

Thanks
Fritz

**Comment by MehmetGoktay** [comment]
Hi Fritz,

Mostly it does self pollination thus I would not expect to so much see heterozygosity. 

Thank you very much for your answer I will try -f 0.8

Best,
Mehmet
