### ISSUE TITLE
ngmlr and sniffles applied to de novo assembly

### ISSUE THREAD

**Issue by sjin09** [fritzsedlazeck/Sniffles#50]
Dear Fritz,

We have assembled a large mammalian genome using 90X of SMRT platform data. The base-accuracy of the assembly is often assessed using alignment of HiseqX paired-end reads to the assembly and calculating the number of homozygous snps and homozygous indels. 

I wanted to use long-reads to assess the assembly in a similar manner. I am using ngmlr and sniffles to align the long-reads back to the assembly and to genotype homozygous structural variations  against the assembly. I have used the following cmd for this purpose. 

`${SNIFFLES_PATH}/sniffles -m input.bam -v output.vcf -t 10 -l 50 --report_seq --cluster --genotype`

I have found approximately ~20,000 structural variations against the de novo assembly. I am quite surprised by the fact that there the genotype is 0/0 for the structural variation. I was expecting the genotype to be 0/1 or 1/1. Could you provide some insights into this?

I look forward to your response. 

Best,
Sangjin Lee

**Comment by fritzsedlazeck** [comment]
Dear Sangjin Lee,
I think that is a clever way. 
So with the 90x coverage you can find often artifacts that simply accumulate. They will likely be marked as IMPRECISE and often have a genotype of 0/0 indicating a very low support or frequency of reads supporting them. The AF= tag gives you the allele frequency of each event. 
Without knowing your sample I assume you will find alot of false insertion and translocation calls. 
Translocation can indicate some evidence that some contigs/scaffolds could further be joined. 
Insertions accumulate sometimes due to a base calling error/ polymerase stuttering during the sequencing. PacBio is working on it and it should get improved over the next version of the basecaller. 

0/1 SVs can happen as these are the heterozygous SVs. As you know most of the assemblers only report one sequence as a representation. 

So what I would do is to focus on the 1/1. These should either mark problems from NGMLR+ sniffles or form the assembly. You might want to pinpoint these regions and also look at the short read evidence for these regions.

I hope this is helping you. Otherwise feel free to ping me and we can chat. 
Cheers
Fritz

**Comment by sjin09** [comment]
Hey Fritz,

Thank you for the swift response. This is a really helpful response. I would love to be able to discuss this further with you, but I would to do so in private as the data is unpublished. If there are any additional problems, can I send you an email through your baylor college of medicine email address?

I will concentrate on the homozygous genotypes for now, visualize the long-read bam file and short-read bam file using IGV. I guess I could potentially increase the number of minimum reads required for genotyping to reduce the number of false positive variants.
 
Best,
Sangjin Lee

**Comment by fritzsedlazeck** [comment]
Yes feel free to ping me. The fastest is over my gmail: fritz.sedlazeck@gmail.com ,but the bcm also works.

I think it would be great to stick the heads together and come up with a small pipeline that can automatically assess this. Just an idea, but I am happy to discuss further options.
Cheers
Fritz
