### ISSUE TITLE
no SVs were called in large gap

### ISSUE THREAD

**Issue by hjt1129** [fritzsedlazeck/Sniffles#509]
hi, 
I compared two assembled genome to find SVs between them, when i open the bam file in igv (see the figure), it possess a large gap between 25700kb to 26000kb, so why the sniffles can not detect it, even if i used --no-qc? is it too long or something else?

![image](https://github.com/user-attachments/assets/93116b72-2019-478f-b63c-2aa65f30a572)

**Comment by fritzsedlazeck** [comment]
Dear @hjt1129 
We would need to know a bit more.  What's your coverage? You show here one read I think? That would not be enough to call an SV.  To make sure. Please klick on link supplementary files. This should display a thin line between the segments, which indicates that the two segments are actually connected. Otherwise it's just a lack of coverage of one read which would not qualify as an SV. 

Thanks 
Fritz

**Comment by hjt1129** [comment]
hi, 
Yes, it only has one contig because it was the assembled genome that mapped to the reference genome. It shows the same contig (ptg000254l) for the sequence before  25.7k and that after 26.0k. Actually, two SVs (position 25555966 with the SVLEN=10607; ) was also called by sniffles where also has only one read (i.e. the ptg000254l contig). So it's confused me why this large gap can not be called. 

![image](https://github.com/user-attachments/assets/f0e577ae-70f3-4662-a871-38154e8f52b0)

![image](https://github.com/user-attachments/assets/d239af13-42f7-4a11-bde4-1bfdffa0bd16)

**Comment by fritzsedlazeck** [comment]
ah so thats whats going on. .. Sniffles is not designed for an assembly alignment. I would recommend using Dipcall for example.  Sniffles is for when you have mapped long reads to the reference and want to obtain SV. 

Good luck 
Fritz
