### ISSUE TITLE
Use cs tag

### ISSUE THREAD

**Issue by fritzsedlazeck** [fritzsedlazeck/Sniffles#51]
Expand Sniffles to use the CS tag proposed by @lh3 
https://github.com/lh3/minimap2#the-cs-optional-tag

**Comment by fritzsedlazeck** [comment]
Minimap2 will be updated to include MD tag. Thus this is getting irrelevant.

**Comment by lh3** [comment]
I didn't know Sniffles requires MD to work; otherwise I would have --MD earlier. Please let me know if Sniffles requires more SAM features. I'd love to make minimap2 work with it. Thank you!

**Comment by fritzsedlazeck** [comment]
Thanks. Its scans the MD for "small" INDELs and thus dont operate on the reference sequence.

If you include the MD string that is 98% of all the magic. Philipp and I also included a SV tag in NGMLR that indicates for me if a read was truncated because of N's or because of SVs. Happy to explain. 

Thanks.
Fritz

**Comment by lh3** [comment]
Could you give a bit more detail about this SV tag? Thanks.

**Comment by fritzsedlazeck** [comment]
Sure. Happy to discuss also offline. SV is a binary tag in NGMLR to indicate the reason for clipping. 
@philres knows more about the details:
https://github.com/philres/ngmlr/issues/15

This is used to infer larger Ins than read length. 

Thanks
Fritz

**Comment by philres** [comment]
Hi Heng,

The SV:i tag in the NGMLR output contains two bit flags:

`0x1` indicates whether the reference sequence consists of mostly Ns up and/or downstream of the read alignment. Sniffles uses soft-clip information to improve detection of (large) insertions. As a consequence longer regions of Ns in the reference would cause false positives signals as the reads up/down stream of the Ns will all be soft-clipped at the same position of the reference. `0x1` helped to avoid that.
`0x2` is set if > 95 % of the read base pairs were aligned in the particular alignment. Sniffles could compute that from the CIGAR string but since we had the SV tag already at that point we just added it. Don't know if Fritz is still using it.

Hope that helps,
Philipp

**Comment by lh3** [comment]
Thanks much for the explanation, @philres. I will consider to implement this tag but not very soon as @fritzsedlazeck thinks the MD tag alone should work in most cases.
