### ISSUE TITLE
svlen is missing from insertion calls

### ISSUE THREAD

**Issue by sjin09** [fritzsedlazeck/Sniffles#57]
Dear Fritz,

I was wondering if the following issue is an error in sniffles. I have aligned 5X worth of PacBio sequel data using NGMLR and called structural variations using SNIFFLES. I have found cases where insertions are called and insertion sequences are provided, but the SVLEN is missing as the example below shows.

I can approximate the SVLEN from the given SEQ, but I wanted to know what was causing this issue.

5       64184964        7714    N       <INS>   .       PASS    PRECISE;SVMETHOD=Snifflesv1.0.8;CHR2=5;END=64184964;ZMW=1;STD_quant_start=0.707107;STD_quant_stop=0.707107;Kurtosis_quant_start=-1.000000;Kurtosis_quant_stop=-1.000000;SVTYPE=INS;SUPTYPE=AL;SVLEN=NA;STRANDS=+-;SEQ=TGATCACGTTGGAAACACTCTTTTGTAGTGTCTGGAAGGGAAAGATTTGGAGCGCTTTGATGCCCTTTGGTGAACAAGGGCATTTCTTCCCATAAAAATTAGACAGAAGCATTTCTAGAAACTTGTTGTGATGGTGACCCAGCTAAGGAGGACAGTTGAACATTCGTATGATAGAGCAGTGTGAAACACTATTTTTGTGGAACAATGCAAGCAATTGGATATTTGGATAGCTGGAGGGGATTTCGTTGAAAGCGGGATATTCAAATAAAAAGGTAGACAGGAGCATTCTCAGAAATTTTCTTTCTGATGTACTGATATTCAACTCATAGAGTGAAGATTCCCGTTCATAGAGGCAGTTTTGAAACACCTTCTGGAGTATCTGGATGTGGACATGTGGAGCGCTTTGATTGCCTACGGTGAATGAAAAAGGGCAAATATCTTCCCATTAAAACGAGACAGGAAGATTCGGAGAGACAGTGGATGTGTTGTACATCAAGATAGCTAACAGAGTGCGAACCCTTTCTTTGTTACAGAGCAGCTTTGAAACGCTATTTTTGTTGGATCTGCAAATGGATATTTAGAGTTGCTTTTTACAGATATCGTTGGAATAGGGAAAATCGTCAACAAAATCTGGACAGAGCATTCTCACCAAAACTTCTTGTTGATGTGTGTCCTCAACGTAACAGAGTGAAAACTTTCTTTTCGATGCCTAGCAGTTTGGAAAAACCTTGTTGTAGAACACTGTAAGGGGATATTGGGATTGCTCTAAGATTTCGTTGGAAACGGGAATATCAATCATCTAAAATCTAGACAGAAGCACTTATTTAGAAAAATCTTGGTGATATCTGCATTCAAGTCAGAAGAGTTGAACATTCCTTACTTGAGATCGTTTGAAACACCCTTTGGAAAGAATCTGGAATGTGGAATTTGGAGCGCTTTATGCCTTTGGTTGAAAAGGAAACGTCTTCCAATAAAAGCTAGACAGAAAGCATTCTCAGAAATTGTTTCCTTGATGTGTGTACTCAACTAAAAGAGTTGAACCTTTCTATTGATTGTAGAGCAGTTTAACACACTCTTTTTGTGGATTCTGCAAGTGGATATTTGGATTGCTTTGAGGAGGTTCGTTGGAAGCGGGAATTCGTTAAACACACTAGAAGCACATTTCCCAGAAATGTTCTGGATATTTCAATTCAACTCATAGAGATGAACATGGCCTTCATAGAGCAGGTTGAAACACTCTGTTTTGTAGTTGTGGAAGTTGGACATTGTCGATCGCCTGGACGCCTACGGTTGAATGTGAAAAAAGGAGGAAAATTATATTCCAGAAAAAGGACAGAAGCATTCTCAGGAAACTGTGGTTGATTTGGTCCTCAACTAACAGAGTTGACTTTGCCTATGATAGGAGAGCAGTTTTTGAAACCCACTCTATTTTCATGATCTTGCAAGGGGATATTTGGATAGCTTGGAGATTTAGTTGGAAGCGGGCATTCAAAGTAAAGTAGACAGCAGCATTCGCAGATAAATTATTTTCTGATCGATGCATCAAATCATTAGAGTTGAACATTTCCTTTGTCATAGGGCAGGTTTGAAAGACCTCTTTTCTCGTAGTATCTGGCTGTGGAATTTGTGAGCGTTGAGCCTACGGTGAAAAAGTAAATATCTTCCCATTTAAAAACGAGACAGAAGGATTTGAGAAAACAAGTTGTGAATGGTGTACTCAGGCTAACAGAGTGAACCTTCTCTTTGATGCCAGTAGTTTGGAAACACTCTTTTTTGTAGAATAGGGAAACTGTAAGGGTGATTGGGATAGCTCTAATGATTTCGTTGGAAACGGAATATAATACACTAAAAATCGAGACAGAAGCCCTTTCAGAAAATACTTGTGATATCTGCATCAAGTCAACAGCGGTGTTCGAACATCAGCTTTCTTAGACACGTGGAAAACGTCTTGTTGTAGGGGGTCTGGAAGTGGTGGACATTTGGAAGCGCTTTGATGCCTT;RE=2;AF=0.4      GT:DR:DV        0/1:3:2

Best,
Sangjin Lee

**Comment by fritzsedlazeck** [comment]
Dear Sangjin,
thanks for reporting this. Do you see other cases where this happens apart from this?

The reason I am asking is that I think I know what happens and there is not much I can do about it. 
So this insertion is supported by an Alignment event. This means that either it is within the read or on the edge (clipped bp). The latter is more likely given what I see. So basically Sniffles detects two reads that are soft clipped on that location, but cannot estimate the length. We cannot estimate the length due to that the read doesnt seem to be longer than the putative insertion. It still tries to give you a sequence but the sequence in this case wont be complete. 

Furthermore, I see that the reads are both originating from the same ZMW, which kinda worries me. 
Due to the low ZMW value I would discard this SV. 
I hope that helps.

Let me know if you have find other cases like this and I am happy to look at them. Plus it would be extremely helpful if you could extract some of the reads in that region and send it over if you find additional cases.

Thanks
Fritz

**Comment by mschatz** [comment]
Would it be helpful if we reported the insertion length as 999999999 or so
if Sniffles detects an insertions but the reads arent long enough to
determine the insertion length?

Mike

**Comment by fritzsedlazeck** [comment]
Mhm its a general problem. In theory we should list a number due to the specs, but any number will be misleading... 
Happy to take suggestions. I can try to make an extra flag for exactly these scenarios...

**Comment by sjin09** [comment]
I would assume these type of insertions would have the signature of "single hard-stop" described Mark Chaisson in the paper "resolving the complexity of the human genome using single-moelcule sequencing"

It would be nice to have a flag that describes what type of structural variation it was. Then normal users would have a better idea why some metric is missing. I was hoping to just use the SEQ and calculate the SVLEN as well. 

I can also calculate the correct SVLEN from the insertion called from this site using the assembly.

**Comment by fritzsedlazeck** [comment]
Sure, i will incorporate a flag for these events in the next release. 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Hi,
I just pushed the code that includes now a flag for these kind of Insertions. 
Instead of PASS it will mark the SV as "UNRESOLVED" . 
Could you give it a try to see if that is the case for the INS that you mentioned above. 
Thanks
Fritz

**Comment by sjin09** [comment]
Fritz, I can confirm that the issue has now been resolved.

**Comment by fritzsedlazeck** [comment]
Great thanks for reporting back.
Cheers
Fritz

**Comment by FiniDG-HAN** [comment]
I found the svlen 999999999 and was surprised at first, but found the reason in this issue. But I have a follow-up question to this.

So I have some insertions of 10000. And minimap2 mapping made it slightly easier to find according to my findings. However, when I zoomed in on one of these 10000 INS, I found out that the soft clipping on the left of the INS varied between 3 - 12.768 and on the right between 280 - 15.148. with an average around 5000 in length (the numbers here represent the soft-clipped length, not the actual read length). So I was wondering how Sniffles determines the length of the insertions, because a few reads (only 5) spanned the whole insertion region (soft-clipped >10000), but most reads would overlap if left and right soft-clipped reads were aligned together.

a bit like this
```
-----|---------------------     -------|-----
-----|-----            ----------------|-----
-----|-------------------------  ------|-----
-----|----------      -----------------|-----
                                       
    INS                                INS
    START                              END
```

Does Sniffles use soft-clipped information from both sides or does it just considers reads that span the whole INS?

**Comment by fritzsedlazeck** [comment]
Hi yes we are using soft clipped information but just as the information that there could be an insertion. We cannot derive the length of it. Now if we have mixed signals clipped and a few spanning reads Sniffles should take the clipped as supporting and report the spanning for the length estimate. There are some thresholds build in and it can be the case that with 5x you see only one or two reads spanning in which case Sniffles might not report it.

Does that help?
Cheers
Fritz

**Comment by FiniDG-HAN** [comment]
Well what if for example there are no spanned reads (so no soft-clipping higher than 10.000 bp), but all the other soft-clipping around the undetermined region is around 8000 bp for example, then there would be an overlapping region of about  3000. So that way you should be able to determine a length of 10.000 right?

**Comment by fritzsedlazeck** [comment]
No I don't think you can use soft clipping like that. You can only estimate that the onsertion is longer than 8kbp. 
What determines the overhand is the length of the reads and their position. Meaning how close they can still be positioned next to the breakpoint.

For example if the insertion is eg. 100kbp. And your reads are on average 20kbp. Then the longest clipping you might be able to observe will be 18kbp at that location, right? So correctly indicating that the Ins is 18kbp+ long, but that would still be a wrong estimate. This, we use this strange number since we have to give some number and I dicate it as unresolved in the VCf file.

Does that makes sense?
Cheers
Fritz

**Comment by FiniDG-HAN** [comment]
See the updated comment above (maybe we missed each other). But a 20kbp read will never overlap in a  100kbp region, while it could happen in my example above

**Comment by fritzsedlazeck** [comment]
Sorry I missed that the clipped parts are overlapping. In this case there is hope, but Sniffles does not check this right now. It's interesting and would be nice to dig into this. We are also working on crosstich a local assembly based on sniffles output. Might be interesting to check what happens here ...
Thanks
Fritz

**Comment by FiniDG-HAN** [comment]
Interesting indeed to align based on sniffles results. I think it could solve a lot!
However, I think this needs time to implement? So i just have to see this as a possible future feature?

**Comment by fritzsedlazeck** [comment]
In this one case lowering the -s will not help. There are some haedcoded thresholds before I make an estimate for the size insight to ensure that I have some measurements to support the estimate.

Thanks for pointing that out 
Fritz
