### ISSUE TITLE
Most calls not genotyped, discrepancies in number of variants

### ISSUE THREAD

**Issue by wdecoster** [fritzsedlazeck/Sniffles#66]
Hi Fritz,

As discussed in other thread(s) I'm using sniffles with -Ivcf (for which the vcf is generated by combining two vcfs using survivor). Some numbers:

vcf1_calls: 19460 variants
vcf2_calls: 30710 variants
combined_calls: 35033 variants

vcf1_genotyped: 33662 variants
vcf2_genotyped: 33662 variants
combined_genotypes: 32075 variants

Question1: with combined calls = 35033, why do I get less genotyped positions?

Question2: How/why did I lose 33662 - 32075 = 1587 variants while merging both genotyped vcfs?
survivor command used:

`SURVIVOR merge samples.fofn 1000 0 1 0 0 0 combined_genotypes.vcf`

Question3: When checking the genotypes in this combined file, 26041 out of 32075 variants from this file have twice 0/0. So only 1/5th of the variants are actually genotyped.

Does this make sense? Did I do something wrong? Should I provide more information somewhere?

Thanks again,
Wouter

**Comment by fritzsedlazeck** [comment]
Ok lets see if I got everything:
So SURVIVOR merges entries if they are within the 1000bp. 
So 30710+19460 does not need to result in 50,000+.  

Ad Q1: The merging within SURVIVOR is strictly based on the here 1kbp distance. So there are variations that are merged within the sample and across the sample. 

Ad Q2: I would need to see the VCF as input for Sniffles. We would need to check if there are some sizes that gets collapsed etc. 

Ad Q3: How different are the samples? I am wondering if the low 0/0 is because the breakpoints are getting moved from the merge and thus Sniffles does not re identify them. We might need to take this offline (fritz.sedlazeck@gmail.com) and discuss this. There is currently a wobble parameter in Sniffles, but that is not directed towards that potential problem. 

A user never does something wrong, its always my fault ;). Haha

Thanks
Fritz

**Comment by wdecoster** [comment]
Q1: Got it, makes sense.

Q2 & Q3: I'll send you an email

Thanks!

**Comment by fritzsedlazeck** [comment]
This got resolved offline over an update of SURVIVOR. 
Thanks!
Fritz
