### ISSUE TITLE
Heterozygous SVs and homozygous SVs

### ISSUE THREAD

**Issue by yilunhuangyue** [fritzsedlazeck/Sniffles#72]
Hi, I have assembled a hyplotype  genome and  then sequenced the diplotype genome of the same species by Pacbio. I want to phase the other hyplotype, so I mapped the sequence by ngmlr and call SVs by Sniffles, but more 30%  are homozygous SVs. I am not sure if I should I use these  homozygous SVs. Do these homozygous SVs mean assembly errors?
Thanks for any help.

**Comment by fritzsedlazeck** [comment]
Hi,
thanks for reaching out. 

Quite frankly the genotype part of the program is not the most sophisticated and I know some limitations. For example, if a region is quite noisy it happens that the reference allele is underestimated. Or if two variations are close to each other or overlapping the genotype for them will also be skewed towards the homozygous alternative allele. 

It is basically due to bookkeeping of which reads support SVs and which are pure reference supporters. Right now its a boolean decision and this causes in some scenarios problems. I am trying to improve this, but I dont have a fix yet. 

I hope that helps to understand this effect and yes I am sure some (hopefully few) might be artifacts. This is often hard to avoid. You can filter based on read support and what also sometimes help is precise vs. imprecise although with the later you might loose SV in highly repetitive regions. 

I will keep that open until I found an improvement.
Thanks
Fritz

**Comment by yilunhuangyue** [comment]
Hi Fritz,
Sorry for the late reply. 
I  decided to test the SVs by PCR for homozygous SVs and I will post my result here.
By the way, I want to phase SVs by Hapcut2, and I can not get any result when I use SVs from Sniffles as input, I am not sure if it is the problem of vcf format. Have you phase SVs by Hapcut2 before?
Thanks for your help again.

**Comment by fritzsedlazeck** [comment]
That would be very interesting.

We are using Hapcut2, but I think it is not able to phase the SVs directly. What we are doing is phase the SNPs with Hapcut2 and then run Sniffles with -n -1 to report all read names. 
Subsequently you provide all this information to Crosstich: https://github.com/schatzlab/crossstitch

Let me know if you have further questions. 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Please let me know if there are any updates and feel free to open the issue again.
Thx
Fritz

**Comment by skose82** [comment]
> Hi Fritz, Sorry for the late reply. I decided to test the SVs by PCR for homozygous SVs and I will post my result here. By the way, I want to phase SVs by Hapcut2, and I can not get any result when I use SVs from Sniffles as input, I am not sure if it is the problem of vcf format. Have you phase SVs by Hapcut2 before? Thanks for your help again.

Hi [yilunhuangyue](https://github.com/yilunhuangyue),

I am currently looking into this question too. I like the idea os running a PCR to check hom SVs. Do you. happen to have these results/made progress since your last post? Would you be happy to provide the protocol you used?

Best wishes
