### ISSUE TITLE
comparing ngmlr+sniffles with minimap2+sniffles

### ISSUE THREAD

**Issue by ramcn** [fritzsedlazeck/Sniffles#90]
Hi,

I am comparing the minimap2+sniffles combination with ngmlr+sniffles combination for nanopore dataset.
I used the rel5-guppy-0.3.0-chunk10k.fastq.gz nanopore dataset and below options for ngmlr and sniffles.

NGMLR: --match 3 --mismatch -7 --gap-decay 0.1 
SNIFFLES: --genotype --cluster -s 5 -d 1000

Below is the SV statistics I got using SURVIVOR. Could you please let me know if this along the expected performance or I can get better results using ngmlr+sniffles combination ?
![ngmlr-mm2](https://user-images.githubusercontent.com/2152628/43654733-7b9032a0-9709-11e8-83cd-aebd70decca9.png)

**Comment by mschatz** [comment]
If Im reading this correctly, thats a very high number of mutations with
Minimap2 that far exceeds anything reported in the literature. I would
expect the majority of those calls to be false positives

Mike

**Comment by fritzsedlazeck** [comment]
Hi,
why did you ran ngmlr with these parameters? There is an ont parameter -x ont.  Also minimap2 has specific parameter recommendation for ONT.

And is the Sniffles -s 5 because of the coverage? 

Plus SURVIVOR does only report TRA in all length categories. It is also a bit strange that Sniffles does not report any TRA. 

If you want to do such a comparison I would suggest SURVIVOR merge to merge the two data sets and check them out this way over the flags reported in the INFO field. 

Overall we see some improvements in the alignments compared to minimap2. People told me that with carfully tuning you can improve things.

**Comment by ramcn** [comment]
Thanks for the quick comments. The parameters I used were derieved from ngmlr notes for rel3 dataset. [[link](http://labshare.cshl.edu/shares/schatzlab/www-data/fsedlaze/NA12878_nanopore/version1.0/)]

Let me explore a bit more about the options and parameters like "-x ont" and do some tuning and evaluate if things improve using SURVIVOR merge option Also if you can recommend any tool/method to compare with ground truth and identify the false positives it will be helpful.

**Comment by fritzsedlazeck** [comment]
Yeah we are often using SURVIVOR merge to compare the VCF files and then go forward with that. 
Let me know if you have further questions. 
Thanks
Fritz

**Comment by ramcn** [comment]
Hi Fritz,

Could you please validate the below steps to use survivor merge to compare VCF files. Here is what I have go so far, but hasn't given me much comparative results.

$ cat sample_files 
rel5-mm2-sniff-sorted.vcf
rel5-ng-sniff-sorted.vcf

$ SURVIVOR merge sample_files 1000 2 1 1 0 30 sample_merged.vcf

$ SURVIVOR stats sample_merged.vcf -1 -1 -1 res
Processing: 16301
Parsing done: 
Tot	DEL	DUP	INS	INV	TRA
16301	9407	46	6800	48	0

**Comment by fritzsedlazeck** [comment]
Hi,
the way you ran it requires that both data sets agree. 
i would  run it with 1000 1 1 0 0 30 . This way the type is constrained. 
You would then need to dig into the file to get some more interesting stats out of it.
Cheers
Fritz

**Comment by fritzsedlazeck** [comment]
Oh and as I said before consider the different parameters for mapping and what is available for coverage (-s 5) or is that the 28x that it was previously?
Cheers
Fritz

**Comment by fritzsedlazeck** [comment]
Hi,
Great keep me posted. I thought something has to be off since no tra we're reported.
Cheers
Fritz

**Comment by ramcn** [comment]
Hi Fritz,

I needed some help to figure out how to compare with dbvar dataset. Below is the method I am using, but not able to get some useful info.

1. Get the GRCh37.nr_deletions.bed from dbvar SV dataset
2. Use survivor eval command to find TP and FP.
SURVIVOR eval ngmlr-sniffles.vcf  GRCh37.nr_deletions.bed 10 eval_res

Any other alternate method I can use?

**Comment by fritzsedlazeck** [comment]
Sv eval just works on the simulated input. You need to convert the bed into a VCf (bedtovcf) then merge it.

**Comment by ramcn** [comment]
Hi Fritz,

I am not able to find the tool to convert bed to vcf. Could you please point me to the tool you are referring to?

**Comment by fritzsedlazeck** [comment]
Look at the tool you are using already to merge VCf files.

**Comment by ramcn** [comment]
Hi Fritz,

Thanks for the pointer. I was able to try out the below method and get some stats. Although I see very low values so kind of reviewing if I missed anything.

Here is the method I used:
1. Get the VCF files for each dbvar ground truth
SURVIVOR bedtovcf GRCh37.nr_deletions.bed DEL  GRCh37.nr_deletions.vcf
SURVIVOR bedtovcf GRCh37.nr_duplications.bed DUP  GRCh37.nr_duplications.vcf
SURVIVOR bedtovcf GRCh37.nr_insertions.bed INS  GRCh37.nr_insertions.vcf

2. For each DEL, DUP and INS dbvar vcf file, merge with ngmlr and mm2 vcf and get stats
SURVIVOR merge sample_files_dbvar_ngmlr 1000 2 1 1 0 10 sample_merged_ngmlr.vcf
SURVIVOR merge sample_files_dbvar_mm2 1000 2 1 1 0 10 sample_merged_mm2.vcf
SURVIVOR stats sample_merged_ngmlr.vcf  10 10000 -1 res
SURVIVOR stats sample_merged_mm2.vcf  10 10000 -1 res

3. Below are the stats I got for DEL, DUP and INS. 
![dbvar-stat1](https://user-images.githubusercontent.com/2152628/43993457-f0e322a0-9d4a-11e8-94c8-30eabc0af648.png)

**Comment by fritzsedlazeck** [comment]
Well you see these low values because you compare different things. You are comparing any SV with SV from NA12878. Can you explain why dbvar should include the true set???
Plus you must check if the coordinates are on the same human genome build than what you used for mapping etc. 

I dont think you laid out the mapping + calling parameters that you used. 
You need further to check if the ONT data was basecalled with the newest version or still with the older one. The latter has multiple artificial deletions. Furthermore, you should compute precision and recall.

Overall this went far beyond an issue on github for Sniffles. So thus I am closing this. 
Thanks
Fritz
