### ISSUE TITLE
confused by the position

### ISSUE THREAD

**Issue by xinshuaiqi** [fritzsedlazeck/Sniffles#93]
Hi, I am confused by the position information between the vcf and bedpe format.

For example, an inversion would be:
in vcf format:
**chr**: **starting_position** to **(starting_position+SVLEN)**
**chr2**: **(END - SVLEN)** to **END** 

in bedpe format:
**chr**: **Leftmost_starting_position** to **rightmost_starting_position** 
**chr2**: **Leftmost_enf_position** to **rightmost_end_position** 
and SVLEN = **rightmost_starting_position** - **Leftmost_starting_position**

Am I right? Otherwise, please correct me.

**Comment by fritzsedlazeck** [comment]
In principal yes. However, END-SVLEN is not necessary Start because Sniffles reports the best supported start and stop which does not necessary agree to the best supported length. 

In addition, for insertions the start and end reflects the location of the SV and not the length.

Did you see something strange?  I have to admit I dont use the Bedpe option so I neglected it over the past months. 

Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
We cannot always predict the precise location. If that is the case I list the interval.
Cheers
Fritz
